# specify the version of docker-compose
version: '3.8'

services:
  web:
    volumes:
      - .:/app
      -  /app/node_modules/bcrypt
    environment:
      - API_URL= http://localhost:3000/
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000